<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>WindowsOptimizer</AssemblyName>
    <RootNamespace>WindowsOptimizer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="..\..\packages\software-master-list.txt" Link="software-master-list.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
